In [35]:
#import pandas as pd
#from google.colab import files

#uploaded = files.upload()

In [36]:
import pandas as pd
#A random file with trips
df = pd.read_csv('context_dataset_v1_skm.csv')
df

Unnamed: 0           time             datetime        lat        lng  \
0               0  1525666992353  2018-05-07 05:23:12  43.702109  10.400969   
1               1  1520875794472  2018-03-12 17:29:54  43.719917  10.422036   
2               2  1521047383369  2018-03-14 17:09:43  43.719917  10.422036   
3               3  1520872866143  2018-03-12 16:41:06  43.718449  10.423058   
4               4  1520872926143  2018-03-12 16:42:06  43.718449  10.423058   
...           ...            ...                  ...        ...        ...   
45676       45676  1522411614683  2018-03-30 13:06:54  43.718588  10.422543   
45677       45677  1522411674683  2018-03-30 13:07:54  43.718588  10.422543   
45678       45678  1522411734683  2018-03-30 13:08:54  43.718588  10.422543   
45679       45679  1522411794683  2018-03-30 13:09:54  43.718588  10.422543   
45680       45680  1522411854683  2018-03-30 13:10:54  43.718590  10.422563   

       wifi_connected  sensor_light_mean  sensor_accelerometer_x_mean  \
0                   0           0.491083                    -0.841768   
1                   0        2313.365000                     0.090955   
2                   0        4693.660000                    -0.081390   
3                   0         399.206400                    -0.017048   
4                   0         358.872934                    -0.012993   
...               ...                ...                          ...   
45676               1        5540.054054                    -0.236280   
45677               1        5540.054054                     0.046685   
45678               1        5540.054054                    -0.906800   
45679               0        5540.054054                    -0.180495   
45680               0        5540.054054                    -1.395840   

       sensor_accelerometer_y_mean  sensor_accelerometer_z_mean  ...  \
0                        -9.798033                     0.893719  ...   
1                        -0.035095                     9.941500  ...   
2                        -0.004915                     9.928235  ...   
3                        -0.058225                     9.914915  ...   
4                        -0.063340                     9.914752  ...   
...                            ...                          ...  ...   
45676                    -9.867495                    -0.841630  ...   
45677                    -9.941655                    -1.194635  ...   
45678                    -9.309720                    -2.164250  ...   
45679                   -10.570415                    -1.179730  ...   
45680                    -9.512935                    -1.189455  ...   

       sensor_linear_acc_y_mean  sensor_linear_acc_z_mean  \
0                     -4.835157                  0.029616   
1                      0.000559                  0.135715   
2                      0.021426                  0.122015   
3                      0.005610                  0.000917   
4                     -0.000354                  0.001047   
...                         ...                       ...   
45676                 -0.531366                  0.948790   
45677                 -0.586462                  0.568400   
45678                  0.067008                  0.171119   
45679                 -1.232717                  0.417479   
45680                  0.017971                  0.072995   

       sensor_rotation_vec_x_mean  sensor_rotation_vec_y_mean  \
0                       -0.531964                   -0.058802   
1                       -0.004916                   -0.000646   
2                       -0.004425                   -0.001167   
3                       -0.002664                   -0.000225   
4                       -0.002985                   -0.000889   
...                           ...                         ...   
45676                   -0.232583                    0.727089   
45677                   -0.244852                    0.561846  

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45681 entries, 0 to 45680
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Unnamed: 0                   45681 non-null  int64  
 1   time                         45681 non-null  int64  
 2   datetime                     45681 non-null  object 
 3   lat                          45681 non-null  float64
 4   lng                          45681 non-null  float64
 5   wifi_connected               45681 non-null  int64  
 6   sensor_light_mean            45681 non-null  float64
 7   sensor_accelerometer_x_mean  45681 non-null  float64
 8   sensor_accelerometer_y_mean  45681 non-null  float64
 9   sensor_accelerometer_z_mean  45681 non-null  float64
 10  sensor_gravity_x_mean        45681 non-null  float64
 11  sensor_gravity_y_mean        45681 non-null  float64
 12  sensor_gravity_z_mean        45681 non-null  float64
 13  sensor_gyroscope

In [38]:
df.describe(include="all")

Unnamed: 0          time             datetime           lat  \
count   45681.00000  4.568100e+04                45681  45681.000000   
unique          NaN           NaN                45681           NaN   
top             NaN           NaN  2018-05-07 05:23:12           NaN   
freq            NaN           NaN                    1           NaN   
mean    22840.00000  1.523143e+12                  NaN     43.708539   
std     13187.11316  2.036985e+09                  NaN      0.037505   
min         0.00000  1.520871e+12                  NaN     43.550685   
25%     11420.00000  1.521388e+12                  NaN     43.701246   
50%     22840.00000  1.522002e+12                  NaN     43.702756   
75%     34260.00000  1.525434e+12                  NaN     43.714339   
max     45680.00000  1.526323e+12                  NaN     44.036749   

                 lng  wifi_connected  sensor_light_mean  \
count   45681.000000    45681.000000       45681.000000   
unique           NaN             NaN                NaN   
top              NaN             NaN                NaN   
freq             NaN             NaN                NaN   
mean       10.431250        0.689871         937.894854   
std         0.072024        0.462551        2355.457365   
min        10.120893        0.000000           0.266412   
25%        10.402320        0.000000           3.147463   
50%        10.416215        1.000000          31.209108   
75%        10.421536        1.000000         269.060000   
max        11.247447        1.000000       16136.067714   

        sensor_accelerometer_x_mean  sensor_accelerometer_y_mean  \
count                  45681.000000                 45681.000000   
unique                          NaN                          NaN   
top                             NaN                          NaN   
freq                            NaN                          NaN   
mean                      -0.074417                    -0.197063   
std                        1.994505                     2.880532   
min                      -10.451054                   -11.341595   
25%                       -0.086746                    -0.177370   
50%                        0.011595                    -0.002205   
75%                        0.130984                     0.187133   
max                        9.915660                     9.917055   

        sensor_accelerometer_z_mean  ...  sensor_linear_acc_y_mean  \
count                  45681.000000  ...              45681.000000   
unique                          NaN  ...                       NaN   
top                             NaN  ...                       NaN   
freq                            NaN  ...                       NaN   
mean                       8.208775  ...                 -0.016487   
std                        4.069894  ...                  0.214175   
min                       -9.747825  ...                 -6.615375   
25%                        9.649220  ...                 -0.002004   
50%                        9.796048  ...                 -0.000097   
75%                        9.897063  ...                  0.001234   
max                       10.915007  ...                  3.658941   

        sensor_linear_acc_z_mean  sensor_rotation_vec_x_mean  \
count               45681.000000                45681.000000   
unique                       NaN                         NaN   
top                          NaN                         NaN   
freq                         NaN                         NaN   
mean                    0.061983                   -0.022146   
std                     0.167013                    0.192287   
min                    -3.529628                   -1.000000   
25%                    -0.000027                   -0.007760   
50%                     0.001448                   -0.001263   
75%                     0.126604                    0.008476   
max                     3.597762                    0.978355   

        

In [39]:
#View the distribution of the dataset by transport mode class
print(df.groupby('activity_label').size())

activity_label
activity_rec_in_vehicle      395
activity_rec_on_bicycle      236
activity_rec_on_foot        2384
activity_rec_still         41116
activity_rec_tilting         235
activity_rec_unknown        1315
dtype: int64


In [40]:
#View the distribution of the dataset by purpose class (Não Temos!)
#print(df.groupby('purpose').size())

In [41]:
#Eliminate unique/or almost unique columns
df_final=df.drop(['time','lat','lng', 'datetime', 'uid','Unnamed: 0','trajectory_id'], axis=1)
df_final

wifi_connected  sensor_light_mean  sensor_accelerometer_x_mean  \
0                   0           0.491083                    -0.841768   
1                   0        2313.365000                     0.090955   
2                   0        4693.660000                    -0.081390   
3                   0         399.206400                    -0.017048   
4                   0         358.872934                    -0.012993   
...               ...                ...                          ...   
45676               1        5540.054054                    -0.236280   
45677               1        5540.054054                     0.046685   
45678               1        5540.054054                    -0.906800   
45679               0        5540.054054                    -0.180495   
45680               0        5540.054054                    -1.395840   

       sensor_accelerometer_y_mean  sensor_accelerometer_z_mean  \
0                        -9.798033                     0.893719   
1                        -0.035095                     9.941500   
2                        -0.004915                     9.928235   
3                        -0.058225                     9.914915   
4                        -0.063340                     9.914752   
...                            ...                          ...   
45676                    -9.867495                    -0.841630   
45677                    -9.941655                    -1.194635   
45678                    -9.309720                    -2.164250   
45679                   -10.570415                    -1.179730   
45680                    -9.512935                    -1.189455   

       sensor_gravity_x_mean  sensor_gravity_y_mean  sensor_gravity_z_mean  \
0                   3.690201              -7.011099               1.476234   
1                   0.090053              -0.035611               9.805696   
2                  -0.085803              -0.026341               9.806220   
3                  -0.020499              -0.048117               9.806409   
4                  -0.012417              -0.059815               9.806453   
...                      ...                    ...                    ...   
45676               0.032914              -9.336129              -1.790420   
45677               0.002404              -9.348885              -1.707646   
45678              -0.925490              -9.377563              -2.335369   
45679               0.055294              -9.326848              -1.590694   
45680              -1.486983              -9.530261              -1.278110   

       sensor_gyroscope_x_mean  sensor_gyroscope_y_mean  \
0                     0.010872                -0.074200   
1                     0.041042                 0.011238   
2                     0.037719                 0.010877   
3                    -0.000539                 0.000098   
4                     0.000309                 0.000313   
...                        ...                      ...   
45676                -0.003322                -0.051172   
45677                -0.355434                -0.536889   
45678                -0.111475                -0.536334   
45679                -0.060192                 0.408128   
45680                -0.083731                 0.284237   

       sensor_gyroscope_z_mean  sensor_linear_acc_x_mean  \
0                     0.013627                 -3.178609   
1                    -0.000484                  0.000720   
2                     0.005073                  0.004413   
3                     0.000976                  0.000341   
4                     0.000833                  0.001090   
...                        ...                       ...   
45676                -0.167072                 -0.269194   
45677                -0.134759                  0.044226   
45678                -0.288969                  0.020100   
45679                -0.117031                 -0.227864   
45680              

In [42]:
#Simple Label encoding
#Import label encoder
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'activity_label'.
df_final['activity_label']= label_encoder.fit_transform(df_final['activity_label'])

df_final['activity_label'].unique()

array([2, 3, 5, 0, 1, 4])

In [43]:
# Encode labels in column 'label'.
df_final['label']= label_encoder.fit_transform(df_final['label'])

df_final['label'].unique()

array([2, 9, 0, 8, 3, 1, 6, 4, 5, 7])

In [44]:
#1º Classification problem - transport mode
Y1=df_final['activity_label'].to_numpy()  #1st possible dependent variable
type(Y1)

numpy.ndarray

In [45]:
#2nd Classification Problem - purpose
Y2=df_final['label'].to_numpy()  #2nd possible dependent variable

In [46]:
#Dependent variables are removed - 1st Problme
X1=df_final.drop(['activity_label','label'], axis=1).to_numpy()
print(X1)

[[ 0.00000000e+00  4.91082916e-01 -8.41767960e-01 ... -5.88021923e-02
  -2.86727045e-01  2.50000000e+00]
 [ 0.00000000e+00  2.31336500e+03  9.09549996e-02 ... -6.46196335e-04
  -8.80064196e-01  5.00000000e-01]
 [ 0.00000000e+00  4.69366000e+03 -8.13899999e-02 ... -1.16727462e-03
   9.99184890e-01  3.33333333e-01]
 ...
 [ 1.00000000e+00  5.54005405e+03 -9.06800001e-01 ... -6.12670184e-01
   5.13169153e-01  0.00000000e+00]
 [ 0.00000000e+00  5.54005405e+03 -1.80494990e-01 ... -2.94564602e-01
   2.33445115e-01  0.00000000e+00]
 [ 0.00000000e+00  5.54005405e+03 -1.39584000e+00 ...  8.06773034e-02
   3.00281655e-02  0.00000000e+00]]


In [47]:
#Dependent variable is remove - 1st problem
X2=df_final.drop('label', axis=1).to_numpy()
print(X2)

[[ 0.00000000e+00  4.91082916e-01 -8.41767960e-01 ... -2.86727045e-01
   2.50000000e+00  2.00000000e+00]
 [ 0.00000000e+00  2.31336500e+03  9.09549996e-02 ... -8.80064196e-01
   5.00000000e-01  3.00000000e+00]
 [ 0.00000000e+00  4.69366000e+03 -8.13899999e-02 ...  9.99184890e-01
   3.33333333e-01  3.00000000e+00]
 ...
 [ 1.00000000e+00  5.54005405e+03 -9.06800001e-01 ...  5.13169153e-01
   0.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  5.54005405e+03 -1.80494990e-01 ...  2.33445115e-01
   0.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  5.54005405e+03 -1.39584000e+00 ...  3.00281655e-02
   0.00000000e+00  2.00000000e+00]]


In [48]:
#min-max normalization
import pandas as pd
# Min-Max Normalization function
def min_max_normalize(df2):
    return (df2 - df2.min()) / (df2.max() - df2.min())

# Apply Min-Max Normalization
X2 = min_max_normalize(X2)
X2

array([[0.00070238, 0.00073279, 0.00065025, ..., 0.00068462, 0.0008572 ,
        0.00082624],
       [0.00070238, 0.14396778, 0.00070801, ..., 0.00064788, 0.00073334,
        0.00088817],
       [0.00070238, 0.29137811, 0.00069734, ..., 0.00076426, 0.00072302,
        0.00088817],
       ...,
       [0.00076431, 0.34379482, 0.00064622, ..., 0.00073416, 0.00070238,
        0.00082624],
       [0.00070238, 0.34379482, 0.0006912 , ..., 0.00071684, 0.00070238,
        0.00082624],
       [0.00070238, 0.34379482, 0.00061594, ..., 0.00070424, 0.00070238,
        0.00082624]])

In [49]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
# Split dataset into training set and test set
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, Y1, test_size=0.3,random_state=123) # 70% training and 30% test
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, Y2, test_size=0.3,random_state=123) # 70% training and 30% test

In [50]:
#Training and testing a decicion tree classifier - transport mode
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

clf1 = DecisionTreeClassifier().fit(X1_train, y1_train)
y1_pred=clf1.predict(X1_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y1_test, y1_pred))
print("F1-Score:",metrics.f1_score(y1_test, y1_pred, average='macro'))
print("Confusion Matrix:\n", metrics.confusion_matrix(y1_test, y1_pred))

Accuracy: 0.9148485954031376
F1-Score: 0.45777992614547
Confusion Matrix:
 [[   57     3    12    37     0    14]
 [    1    24    26    18     1     7]
 [   11    28   459   171    10    47]
 [   35    19   164 11876    64   148]
 [    0     0     4    46     5    10]
 [   15     7    62   198     9   117]]
