In [5]:
import pandas as pd
#A random file with trips
df = pd.read_csv('trips_dataset.csv')
df

id  closest_distance                       poi    category  duration  \
0    9991         41.167238                       NaN      toilet       872   
1   46166        102.052914                       NaN     parking      1088   
2   46197         67.102374                       NaN     parking       120   
3   46200        171.502718                       NaN      toilet       849   
4   46201         33.740033                       NaN      toilet       242   
5   46214         38.314343  Mac Guls Indopaquistanês  restaurant       723   
6   46218        170.295039                       NaN      toilet       625   
7   46219         34.877078                       NaN        cafe       705   
8   46221         28.566213                  Barclays        bank       284   
9   46231         30.811835                       NaN  restaurant      1100   
10  46234         45.964633                       NaN     parking       604   
11  46235        401.160096           Pastelaria Olpy        cafe       760   
12  46239        107.017155             Farmácia Lobo    pharmacy       408   
13  46248         51.690556                       NaN      toilet       911   
14  46249         42.634306                       NaN     parking       422   
15  46253         71.714159                       NaN        cafe       122   
16  46259         43.566571                       NaN         atm       239   
17  46264         71.224056           Pastelaria Olpy        cafe       559   

    distance_travelled transport_mode           purpose  
0          1079.806233           WALK         EDUCATION  
1          3618.812181           BIKE            HEALTH  
2           175.560423           WALK         EDUCATION  
3          9484.132084            CAR         EDUCATION  
4           340.268882           WALK         EDUCATION  
5          3142.929236           BIKE            HEALTH  
6           902.489331            CAR           LEISURE  
7          8877.241338            CAR               NaN  
8          1264.101898            CAR  SHOPPING-ERRANDS  
9         13651.933656            CAR               NaN  
10        11515.718306            CAR               NaN  
11        13362.482614            CAR               NaN  
12         6402.616047            CAR           LEISURE  
13         1179.357014           WALK         EDUCATION  
14         4734.774036            CAR           LEISURE  
15          129.615327           WALK         EDUCATION  
16          617.852369            CAR  SHOPPING-ERRANDS  
17         9502.735973            CAR  SHOPPING-ERRANDS

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  18 non-null     int64  
 1   closest_distance    18 non-null     float64
 2   poi                 5 non-null      object 
 3   category            18 non-null     object 
 4   duration            18 non-null     int64  
 5   distance_travelled  18 non-null     float64
 6   transport_mode      18 non-null     object 
 7   purpose             14 non-null     object 
dtypes: float64(2), int64(2), object(4)
memory usage: 1.3+ KB


In [7]:
df.describe(include="all")

id  closest_distance              poi category     duration  \
count      18.000000         18.000000                5       18    18.000000   
unique           NaN               NaN                4        7          NaN   
top              NaN               NaN  Pastelaria Olpy   toilet          NaN   
freq             NaN               NaN                2        5          NaN   
mean    44213.277778         86.300073              NaN      NaN   590.722222   
std      8540.791221         89.984856              NaN      NaN   312.405243   
min      9991.000000         28.566213              NaN      NaN   120.000000   
25%     46204.250000         39.027567              NaN      NaN   315.000000   
50%     46226.000000         48.827594              NaN      NaN   614.500000   
75%     46245.750000         94.468225              NaN      NaN   826.750000   
max     46264.000000        401.160096              NaN      NaN  1100.000000   

        distance_travelled transport_mode    purpose  
count            18.000000             18         14  
unique                 NaN              3          4  
top                    NaN            CAR  EDUCATION  
freq                   NaN             11          6  
mean           4999.023719            NaN        NaN  
std            4842.670120            NaN        NaN  
min             129.615327            NaN        NaN  
25%             946.818556            NaN        NaN  
50%            3380.870709            NaN        NaN  
75%            9332.409397            NaN        NaN  
max           13651.933656            NaN        NaN

In [9]:
#View the distribution of the dataset by transport mode class
print(df.groupby('transport_mode').size())

transport_mode
BIKE     2
CAR     11
WALK     5
dtype: int64


In [10]:
#View the distribution of the dataset by purpose class
print(df.groupby('purpose').size())

purpose
EDUCATION           6
HEALTH              2
LEISURE             3
SHOPPING-ERRANDS    3
dtype: int64


In [11]:
#Eliminate unique/or almost unique columns
df_final=df.drop(['id', 'poi'], axis=1)
df_final

closest_distance    category  duration  distance_travelled transport_mode  \
0          41.167238      toilet       872         1079.806233           WALK   
1         102.052914     parking      1088         3618.812181           BIKE   
2          67.102374     parking       120          175.560423           WALK   
3         171.502718      toilet       849         9484.132084            CAR   
4          33.740033      toilet       242          340.268882           WALK   
5          38.314343  restaurant       723         3142.929236           BIKE   
6         170.295039      toilet       625          902.489331            CAR   
7          34.877078        cafe       705         8877.241338            CAR   
8          28.566213        bank       284         1264.101898            CAR   
9          30.811835  restaurant      1100        13651.933656            CAR   
10         45.964633     parking       604        11515.718306            CAR   
11        401.160096        cafe       760        13362.482614            CAR   
12        107.017155    pharmacy       408         6402.616047            CAR   
13         51.690556      toilet       911         1179.357014           WALK   
14         42.634306     parking       422         4734.774036            CAR   
15         71.714159        cafe       122          129.615327           WALK   
16         43.566571         atm       239          617.852369            CAR   
17         71.224056        cafe       559         9502.735973            CAR   

             purpose  
0          EDUCATION  
1             HEALTH  
2          EDUCATION  
3          EDUCATION  
4          EDUCATION  
5             HEALTH  
6            LEISURE  
7                NaN  
8   SHOPPING-ERRANDS  
9                NaN  
10               NaN  
11               NaN  
12           LEISURE  
13         EDUCATION  
14           LEISURE  
15         EDUCATION  
16  SHOPPING-ERRANDS  
17  SHOPPING-ERRANDS

In [12]:
#Simple Label encoding
#Import label encoder
from sklearn import preprocessing
  
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'category'.
df_final['category']= label_encoder.fit_transform(df_final['category'])
  
df_final['category'].unique()

array([6, 3, 5, 2, 1, 4, 0])

In [13]:
# Encode labels in column 'transport_mode'.
df_final['transport_mode']= label_encoder.fit_transform(df_final['transport_mode'])
  
df_final['transport_mode'].unique()

array([2, 0, 1])

In [14]:
#1º Classification problem - transport mode
Y1=df_final['transport_mode'].to_numpy()  #1st possible dependent variable
type(Y1)

numpy.ndarray

In [15]:
#2nd Classification Problem - purpose
Y2=df_final['purpose'].to_numpy()  #2nd possible dependent variable

In [16]:
#Dependent variables are removed - 1st Problme
X1=df_final.drop(['transport_mode','purpose'], axis=1).to_numpy()
print(X1)

[[4.11672379e+01 6.00000000e+00 8.72000000e+02 1.07980623e+03]
 [1.02052914e+02 3.00000000e+00 1.08800000e+03 3.61881218e+03]
 [6.71023735e+01 3.00000000e+00 1.20000000e+02 1.75560423e+02]
 [1.71502718e+02 6.00000000e+00 8.49000000e+02 9.48413208e+03]
 [3.37400326e+01 6.00000000e+00 2.42000000e+02 3.40268882e+02]
 [3.83143428e+01 5.00000000e+00 7.23000000e+02 3.14292924e+03]
 [1.70295039e+02 6.00000000e+00 6.25000000e+02 9.02489331e+02]
 [3.48770779e+01 2.00000000e+00 7.05000000e+02 8.87724134e+03]
 [2.85662127e+01 1.00000000e+00 2.84000000e+02 1.26410190e+03]
 [3.08118345e+01 5.00000000e+00 1.10000000e+03 1.36519337e+04]
 [4.59646325e+01 3.00000000e+00 6.04000000e+02 1.15157183e+04]
 [4.01160096e+02 2.00000000e+00 7.60000000e+02 1.33624826e+04]
 [1.07017155e+02 4.00000000e+00 4.08000000e+02 6.40261605e+03]
 [5.16905562e+01 6.00000000e+00 9.11000000e+02 1.17935701e+03]
 [4.26343061e+01 3.00000000e+00 4.22000000e+02 4.73477404e+03]
 [7.17141588e+01 2.00000000e+00 1.22000000e+02 1.296153

In [17]:
#Dependent variable is remove - 1st problem
X2=df_final.drop('purpose', axis=1).to_numpy()
print(X2)

[[4.11672379e+01 6.00000000e+00 8.72000000e+02 1.07980623e+03
  2.00000000e+00]
 [1.02052914e+02 3.00000000e+00 1.08800000e+03 3.61881218e+03
  0.00000000e+00]
 [6.71023735e+01 3.00000000e+00 1.20000000e+02 1.75560423e+02
  2.00000000e+00]
 [1.71502718e+02 6.00000000e+00 8.49000000e+02 9.48413208e+03
  1.00000000e+00]
 [3.37400326e+01 6.00000000e+00 2.42000000e+02 3.40268882e+02
  2.00000000e+00]
 [3.83143428e+01 5.00000000e+00 7.23000000e+02 3.14292924e+03
  0.00000000e+00]
 [1.70295039e+02 6.00000000e+00 6.25000000e+02 9.02489331e+02
  1.00000000e+00]
 [3.48770779e+01 2.00000000e+00 7.05000000e+02 8.87724134e+03
  1.00000000e+00]
 [2.85662127e+01 1.00000000e+00 2.84000000e+02 1.26410190e+03
  1.00000000e+00]
 [3.08118345e+01 5.00000000e+00 1.10000000e+03 1.36519337e+04
  1.00000000e+00]
 [4.59646325e+01 3.00000000e+00 6.04000000e+02 1.15157183e+04
  1.00000000e+00]
 [4.01160096e+02 2.00000000e+00 7.60000000e+02 1.33624826e+04
  1.00000000e+00]
 [1.07017155e+02 4.00000000e+00 4.080000

In [18]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
# Split dataset into training set and test set
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, Y1, test_size=0.3) # 70% training and 30% test
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, Y2, test_size=0.3) # 70% training and 30% test

In [19]:
#Training and testing a decicion tree classifier - transport mode
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

clf1 = DecisionTreeClassifier().fit(X1_train, y1_train)
y1_pred=clf1.predict(X1_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y1_test, y1_pred))
print("F1-Score:",metrics.f1_score(y1_test, y1_pred, average='macro'))
print("Confusion Matrix:\n", metrics.confusion_matrix(y1_test, y1_pred))

Accuracy: 0.16666666666666666
F1-Score: 0.09523809523809525
Confusion Matrix:
 [[0 2 0]
 [0 1 1]
 [0 2 0]]
