In [30]:
#import pandas as pd
#from google.colab import files

#uploaded = files.upload()

In [31]:
import pandas as pd
#A random file with trips
df = pd.read_csv('context_dataset_v1_skm.csv')
df

Unnamed: 0           time             datetime          lat  \
0               0  1520872866143  2018-03-12 16:41:06  437184494.0   
1               1  1520872926143  2018-03-12 16:42:06  437184494.0   
2               2  1520872986143  2018-03-12 16:43:06  437184632.0   
3               3  1520873046143  2018-03-12 16:44:06  437184632.0   
4               4  1520873106143  2018-03-12 16:45:06  437184632.0   
...           ...            ...                  ...          ...   
45676       45676  1522411614683  2018-03-30 13:06:54  437185879.0   
45677       45677  1522411674683  2018-03-30 13:07:54  437185879.0   
45678       45678  1522411734683  2018-03-30 13:08:54  437185879.0   
45679       45679  1522411794683  2018-03-30 13:09:54  437185879.0   
45680       45680  1522411854683  2018-03-30 13:10:54    4371859.0   

               lng  wifi_connected  sensor_light_mean  \
0      104230581.0               0       3.992064e+16   
1      104230581.0               0       3.588729e+16   
2      104230516.0               0       3.072066e+15   
3      104230516.0               0       3.456171e+15   
4      104230516.0               0       9.787307e+15   
...            ...             ...                ...   
45676  104225426.0               1       5.540054e+15   
45677  104225426.0               1       5.540054e+15   
45678  104225426.0               1       5.540054e+15   
45679  104225426.0               0       5.540054e+15   
45680  104225633.0               0       5.540054e+15   

       sensor_accelerometer_x_mean  sensor_accelerometer_y_mean  \
0                    -1.704826e+15                -5.822472e+16   
1                    -1.299263e+16                -6.334023e+15   
2                    -1.238167e+16                -4.109848e+15   
3                    -1.801071e+16                -8.299019e+14   
4                     1.069637e+16                -9.770349e+15   
...                            ...                          ...   
45676                -2.362800e+16                -9.867495e+15   
45677                 4.668500e+15                -9.941655e+15   
45678                -9.068000e+15                -9.309720e+15   
45679                -1.804950e+15                -1.057041e+16   
45680                -1.395840e+14                -9.512935e+14   

       sensor_accelerometer_z_mean  ...  sensor_rotation_vec_x_mean  \
0                     9.914915e+14  ...                         NaN   
1                     9.914752e+15  ...                         NaN   
2                     9.898847e+15  ...                         NaN   
3                     9.882275e+14  ...                         NaN   
4                     7.506567e+15  ...                         NaN   
...                            ...  ...                         ...   
45676                -8.416300e+15  ...                         NaN   
45677                -1.194635e+16  ...                         NaN   
45678                -2.164250e+16  ...                         NaN   
45679                -1.179730e+16  ...                         NaN   
45680                -1.189455e+15  ...                         NaN   

       sensor_rotation_vec_y_mean  sensor_rotation_vec_z_mean  \
0                             NaN                         NaN   
1                             NaN                         NaN   
2                             NaN                         NaN   
3                             NaN                         NaN   
4                             NaN                         NaN   
...                           ...                         ...   
45676                         NaN                         NaN   
45677                         NaN                         NaN   
45678                         NaN                         NaN   
45679                         NaN                         NaN   
45680                         NaN                         NaN   

       sensor_proximity_mean  multimedia_p

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45681 entries, 0 to 45680
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Unnamed: 0                   45681 non-null  int64  
 1   time                         45681 non-null  int64  
 2   datetime                     45681 non-null  object 
 3   lat                          45681 non-null  float64
 4   lng                          45681 non-null  float64
 5   wifi_connected               45681 non-null  int64  
 6   sensor_light_mean            45681 non-null  float64
 7   sensor_accelerometer_x_mean  45681 non-null  float64
 8   sensor_accelerometer_y_mean  45681 non-null  float64
 9   sensor_accelerometer_z_mean  45681 non-null  float64
 10  sensor_gravity_x_mean        45681 non-null  float64
 11  sensor_gravity_y_mean        45681 non-null  float64
 12  sensor_gravity_z_mean        45681 non-null  float64
 13  sensor_gyroscope

In [33]:
df.describe(include="all")

Unnamed: 0          time             datetime           lat  \
count   45681.00000  4.568100e+04                45681  4.568100e+04   
unique          NaN           NaN                45681           NaN   
top             NaN           NaN  2018-03-12 16:41:06           NaN   
freq            NaN           NaN                    1           NaN   
mean    22840.00000  1.523143e+12                  NaN  4.107568e+08   
std     13187.11316  2.036985e+09                  NaN  9.881243e+07   
min         0.00000  1.520871e+12                  NaN  4.371420e+05   
25%     11420.00000  1.521388e+12                  NaN  4.370123e+08   
50%     22840.00000  1.522002e+12                  NaN  4.370126e+08   
75%     34260.00000  1.525434e+12                  NaN  4.371433e+08   
max     45680.00000  1.526323e+12                  NaN  4.403675e+08   

                 lng  wifi_connected  sensor_light_mean  \
count   4.568100e+04    45681.000000       4.568100e+04   
unique           NaN             NaN                NaN   
top              NaN             NaN                NaN   
freq             NaN             NaN                NaN   
mean    9.326446e+07        0.689871       1.219657e+16   
std     3.042320e+07        0.462551       1.202349e+16   
min     1.042240e+05        0.000000       8.000000e+00   
25%     1.040232e+08        0.000000       3.889406e+15   
50%     1.040233e+08        1.000000       8.852062e+15   
75%     1.041674e+08        1.000000       1.689000e+16   
max     1.124745e+08        1.000000       8.065778e+16   

        sensor_accelerometer_x_mean  sensor_accelerometer_y_mean  \
count                  4.568100e+04                 4.568100e+04   
unique                          NaN                          NaN   
top                             NaN                          NaN   
freq                            NaN                          NaN   
mean                   1.697663e+15                 3.978990e+14   
std                    1.801062e+16                 1.639430e+16   
min                   -7.998805e+16                -7.989243e+16   
25%                   -7.441950e+15                -9.615265e+15   
50%                    1.493000e+15                -1.514893e+12   
75%                    9.478000e+15                 9.366330e+15   
max                    7.976551e+16                 7.991647e+16   

        sensor_accelerometer_z_mean  ...  sensor_rotation_vec_x_mean  \
count                  4.568100e+04  ...                         0.0   
unique                          NaN  ...                         NaN   
top                             NaN  ...                         NaN   
freq                            NaN  ...                         NaN   
mean                   6.780032e+15  ...                         NaN   
std                    8.318762e+15  ...                         NaN   
min                   -7.998545e+16  ...                         NaN   
25%                    2.444335e+15  ...                         NaN   
50%                    9.777235e+15  ...                         NaN   
75%                    9.881225e+15  ...                         NaN   
max                    7.896532e+16  ...                         NaN   

        sensor_rotation_vec_y_mean  sensor_rotation_vec_z_mean  \
count                          0.0                         0.0   
unique                         NaN                         NaN   
top                            NaN                         NaN   
freq                           NaN                         NaN   
mean                           NaN                         NaN   
std                            NaN                         NaN   
min                            NaN                         NaN   
25%                            NaN                         NaN   
50%                            NaN                         NaN   
75%                            NaN                         NaN   
max                        

In [34]:
#View the distribution of the dataset by transport mode class
print(df.groupby('activity_label').size())

activity_label
activity_rec_in_vehicle      395
activity_rec_on_bicycle      236
activity_rec_on_foot        2384
activity_rec_still         41116
activity_rec_tilting         235
activity_rec_unknown        1315
dtype: int64


In [35]:
#View the distribution of the dataset by purpose class (Não Temos!)
#print(df.groupby('purpose').size())

In [48]:
#Eliminate unique/or almost unique columns
df_final=df.drop(['time', 'datetime', 'uid','multimedia_video','multimedia_picture','Unnamed: 0','sensor_linear_acc_x_mean','sensor_linear_acc_y_mean','sensor_linear_acc_z_mean','sensor_rotation_vec_x_mean','sensor_rotation_vec_y_mean','sensor_rotation_vec_z_mean','sensor_proximity_mean'], axis=1)
df_final

lat          lng  wifi_connected  sensor_light_mean  \
0      437184494.0  104230581.0               0       3.992064e+16   
1      437184494.0  104230581.0               0       3.588729e+16   
2      437184632.0  104230516.0               0       3.072066e+15   
3      437184632.0  104230516.0               0       3.456171e+15   
4      437184632.0  104230516.0               0       9.787307e+15   
...            ...          ...             ...                ...   
45676  437185879.0  104225426.0               1       5.540054e+15   
45677  437185879.0  104225426.0               1       5.540054e+15   
45678  437185879.0  104225426.0               1       5.540054e+15   
45679  437185879.0  104225426.0               0       5.540054e+15   
45680    4371859.0  104225633.0               0       5.540054e+15   

       sensor_accelerometer_x_mean  sensor_accelerometer_y_mean  \
0                    -1.704826e+15                -5.822472e+16   
1                    -1.299263e+16                -6.334023e+15   
2                    -1.238167e+16                -4.109848e+15   
3                    -1.801071e+16                -8.299019e+14   
4                     1.069637e+16                -9.770349e+15   
...                            ...                          ...   
45676                -2.362800e+16                -9.867495e+15   
45677                 4.668500e+15                -9.941655e+15   
45678                -9.068000e+15                -9.309720e+15   
45679                -1.804950e+15                -1.057041e+16   
45680                -1.395840e+14                -9.512935e+14   

       sensor_accelerometer_z_mean  sensor_gravity_x_mean  \
0                     9.914915e+14          -2.049859e+16   
1                     9.914752e+15          -1.241748e+16   
2                     9.898847e+15          -5.096975e+16   
3                     9.882275e+14          -7.352869e+15   
4                     7.506567e+15           5.406004e+15   
...                            ...                    ...   
45676                -8.416300e+15           3.291421e+15   
45677                -1.194635e+16           2.404184e+16   
45678                -2.164250e+16          -9.254895e+15   
45679                -1.179730e+16           5.529435e+16   
45680                -1.189455e+15          -1.486983e+16   

       sensor_gravity_y_mean  sensor_gravity_z_mean  sensor_gyroscope_x_mean  \
0              -4.811749e+15           9.806409e+15            -5.394745e+14   
1              -5.981487e+15           9.806453e+15             3.091431e+16   
2               2.879715e+16           9.806348e+15             1.924896e+16   
3              -8.266206e+15           9.806296e+15             7.485962e+15   
4              -9.579664e+15           1.222925e+16             5.346222e+15   
...                      ...                    ...                      ...   
45676          -9.336129e+15          -1.790420e+15            -3.322011e+15   
45677          -9.348885e+15          -1.707646e+16            -3.554343e+15   
45678          -9.377563e+15          -2.335369e+16            -1.114748e+15   
45679          -9.326848e+15          -1.590694e+15            -6.019184e+14   
45680          -9.530261e+15          -1.278110e+16            -8.373101e+15   

       sensor_gyroscope_y_mean  sensor_gyroscope_z_mean         label  \
0                 9.819031e-05             9.757996e+15         Break   
1                 3.134155e+16             8.329773e+15         Break   
2                -7.019043e-06            -6.538391e+15         Break   
3                 6.052399e+15            -9.346008e+14         Break   
4                 7.920258e+15             1.247688e+16         Break   
...                        ...                      ...           ...   
45676            -5.117240e+15            -1.670723e+15  Launch Break   
45677            -5.368892e+15            -1.347589e+16  Launch Break   
45678            -

In [49]:
#Simple Label encoding
#Import label encoder
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'activity_label'.
df_final['activity_label']= label_encoder.fit_transform(df_final['activity_label'])

df_final['activity_label'].unique()

array([3, 2, 5, 0, 1, 4])

In [50]:
# Encode labels in column 'label'.
df_final['label']= label_encoder.fit_transform(df_final['label'])

df_final['label'].unique()

array([0, 9, 2, 8, 3, 1, 6, 4, 5, 7])

In [51]:
#1º Classification problem - transport mode
Y1=df_final['activity_label'].to_numpy()  #1st possible dependent variable
type(Y1)

numpy.ndarray

In [52]:
#2nd Classification Problem - purpose
Y2=df_final['label'].to_numpy()  #2nd possible dependent variable

In [53]:
#Dependent variables are removed - 1st Problme
X1=df_final.drop(['activity_label','label'], axis=1).to_numpy()
print(X1)

[[ 4.37184494e+08  1.04230581e+08  0.00000000e+00 ...  9.81903076e-05
   9.75799561e+15  1.00000000e+00]
 [ 4.37184494e+08  1.04230581e+08  0.00000000e+00 ...  3.13415527e+16
   8.32977295e+15  1.00000000e+00]
 [ 4.37184632e+08  1.04230516e+08  0.00000000e+00 ... -7.01904297e-06
  -6.53839111e+15  1.00000000e+00]
 ...
 [ 4.37185879e+08  1.04225426e+08  1.00000000e+00 ... -5.36333597e+15
  -2.88968827e+15  0.00000000e+00]
 [ 4.37185879e+08  1.04225426e+08  0.00000000e+00 ...  4.08128165e+16
  -1.17031042e+15  0.00000000e+00]
 [ 4.37185900e+06  1.04225633e+08  0.00000000e+00 ...  2.84237277e+15
  -8.85991208e+15  0.00000000e+00]]


In [54]:
#Dependent variable is remove - 1st problem
X2=df_final.drop('label', axis=1).to_numpy()
print(X2)

[[ 4.37184494e+08  1.04230581e+08  0.00000000e+00 ...  9.75799561e+15
   3.00000000e+00  1.00000000e+00]
 [ 4.37184494e+08  1.04230581e+08  0.00000000e+00 ...  8.32977295e+15
   3.00000000e+00  1.00000000e+00]
 [ 4.37184632e+08  1.04230516e+08  0.00000000e+00 ... -6.53839111e+15
   3.00000000e+00  1.00000000e+00]
 ...
 [ 4.37185879e+08  1.04225426e+08  1.00000000e+00 ... -2.88968827e+15
   2.00000000e+00  0.00000000e+00]
 [ 4.37185879e+08  1.04225426e+08  0.00000000e+00 ... -1.17031042e+15
   2.00000000e+00  0.00000000e+00]
 [ 4.37185900e+06  1.04225633e+08  0.00000000e+00 ... -8.85991208e+15
   2.00000000e+00  0.00000000e+00]]


In [55]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
# Split dataset into training set and test set
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, Y1, test_size=0.3) # 70% training and 30% test
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, Y2, test_size=0.3) # 70% training and 30% test

In [56]:
#Training and testing a decicion tree classifier - transport mode
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

clf1 = DecisionTreeClassifier().fit(X1_train, y1_train)
y1_pred=clf1.predict(X1_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y1_test, y1_pred))
print("F1-Score:",metrics.f1_score(y1_test, y1_pred, average='macro'))
print("Confusion Matrix:\n", metrics.confusion_matrix(y1_test, y1_pred))

Accuracy: 0.9055089383436702
F1-Score: 0.41735337703944264
Confusion Matrix:
 [[   46     0    22    37     1    15]
 [    1    26    22    25     0     3]
 [   27    25   432   166     9    67]
 [   39    25   200 11813    58   197]
 [    0     1    10    55     2     8]
 [   13     9    64   189     7    91]]
