In [53]:
#import pandas as pd
#from google.colab import files

#uploaded = files.upload()

In [54]:
import pandas as pd
#A random file with trips
df = pd.read_csv('context_dataset_stage_15min.csv')
df

time_t_15  location_lat  location_lon  wifi_connected  \
0     2018-03-12 16:00:00     43.719917     10.422036               0   
1     2018-03-12 16:15:00     43.719917     10.422036               0   
2     2018-03-12 16:30:00     43.718456     10.423055               0   
3     2018-03-12 16:30:00     43.719525     10.422314               0   
4     2018-03-12 16:45:00     43.718563     10.422838               0   
...                   ...           ...           ...             ...   
3467  2018-05-14 18:30:00     43.701260     10.402326               1   
3468  2018-05-14 18:45:00     43.701239     10.402349               1   
3469  2018-05-14 19:00:00     43.701270     10.402464               1   
3470  2018-05-14 19:15:00     43.701241     10.402420               1   
3471  2018-05-14 19:30:00     43.701549     10.401577               1   

      sensor_light_mean  sensor_accelerometer_x_mean  \
0           6417.333333                    -0.055500   
1           6040.027481                     0.047443   
2            352.725761                    -0.011056   
3           5661.303435                     0.342458   
4             73.245882                     0.185271   
...                 ...                          ...   
3467          51.402142                     0.030118   
3468           2.614647                    -1.212274   
3469           3.052826                    -0.097346   
3470           4.598746                    -0.725779   
3471           2.310801                    -0.075510   

      sensor_accelerometer_y_mean  sensor_accelerometer_z_mean  \
0                        0.019917                     9.932985   
1                       -0.418751                     9.267274   
2                       -0.061413                     9.902697   
3                       -8.678619                    -0.115102   
4                       -9.787095                    -0.971805   
...                           ...                          ...   
3467                     1.358668                     9.230051   
3468                     5.196467                     1.860690   
3469                     3.541464                     3.212960   
3470                     1.857327                     8.079609   
3471                     2.367170                     8.599893   

      sensor_gravity_x_mean  sensor_gravity_y_mean  ...  \
0                 -0.055619               0.019945  ...   
1                  0.046793              -0.419544  ...   
2                 -0.022810              -0.040449  ...   
3                  0.372418              -8.557567  ...   
4                  0.521871              -9.633119  ...   
...                     ...                    ...  ...   
3467               0.101406               1.201873  ...   
3468              -1.510957               4.674029  ...   
3469              -0.133052               3.837788  ...   
3470              -1.385863               1.273659  ...   
3471              -1.003385               1.868450  ...   

      sensor_linear_acc_x_mean  sensor_linear_acc_y_mean  \
0                     0.000061                 -0.000091   
1                    -0.000513                  0.003966   
2                     0.000759                 -0.000138   
3                    -0.031159                 -0.110980   
4                     0.015729                 -0.063115   
...                        ...                       ...   
3467                 -0.030621                  0.181586   
3468                 -0.011051                  0.071136   
3469                 -0.017282                 -0.019066   
3470                 -0.035600                  0.038513   
3471                 -0.026457                  0.000925   

      sensor_linear_acc_z_mean  sensor_rotation_vec_x_mean  \
0                     0.126555                    0.002650   
1                     0.114253                   -0.027221   
2                     0.000673                   -0.00235

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3472 entries, 0 to 3471
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   time_t_15                    3472 non-null   object 
 1   location_lat                 3472 non-null   float64
 2   location_lon                 3472 non-null   float64
 3   wifi_connected               3472 non-null   int64  
 4   sensor_light_mean            3472 non-null   float64
 5   sensor_accelerometer_x_mean  3472 non-null   float64
 6   sensor_accelerometer_y_mean  3472 non-null   float64
 7   sensor_accelerometer_z_mean  3472 non-null   float64
 8   sensor_gravity_x_mean        3472 non-null   float64
 9   sensor_gravity_y_mean        3472 non-null   float64
 10  sensor_gravity_z_mean        3472 non-null   float64
 11  sensor_gyroscope_x_mean      3472 non-null   float64
 12  sensor_gyroscope_y_mean      3472 non-null   float64
 13  sensor_gyroscope_z

In [56]:
from collections import Counter
# Function to replace the label with the most repeated value
def replace_with_most_repeated(label):
    # Split the string into a list
    activities = label.split(';')
    # Find the most common activity
    most_common_activity = Counter(activities).most_common(1)[0][0]
    return most_common_activity

# Apply the function to the 'label' column
df['label'] = df['label'].apply(replace_with_most_repeated)
df['activity_label'] = df['activity_label'].apply(replace_with_most_repeated)

In [57]:
df

time_t_15  location_lat  location_lon  wifi_connected  \
0     2018-03-12 16:00:00     43.719917     10.422036               0   
1     2018-03-12 16:15:00     43.719917     10.422036               0   
2     2018-03-12 16:30:00     43.718456     10.423055               0   
3     2018-03-12 16:30:00     43.719525     10.422314               0   
4     2018-03-12 16:45:00     43.718563     10.422838               0   
...                   ...           ...           ...             ...   
3467  2018-05-14 18:30:00     43.701260     10.402326               1   
3468  2018-05-14 18:45:00     43.701239     10.402349               1   
3469  2018-05-14 19:00:00     43.701270     10.402464               1   
3470  2018-05-14 19:15:00     43.701241     10.402420               1   
3471  2018-05-14 19:30:00     43.701549     10.401577               1   

      sensor_light_mean  sensor_accelerometer_x_mean  \
0           6417.333333                    -0.055500   
1           6040.027481                     0.047443   
2            352.725761                    -0.011056   
3           5661.303435                     0.342458   
4             73.245882                     0.185271   
...                 ...                          ...   
3467          51.402142                     0.030118   
3468           2.614647                    -1.212274   
3469           3.052826                    -0.097346   
3470           4.598746                    -0.725779   
3471           2.310801                    -0.075510   

      sensor_accelerometer_y_mean  sensor_accelerometer_z_mean  \
0                        0.019917                     9.932985   
1                       -0.418751                     9.267274   
2                       -0.061413                     9.902697   
3                       -8.678619                    -0.115102   
4                       -9.787095                    -0.971805   
...                           ...                          ...   
3467                     1.358668                     9.230051   
3468                     5.196467                     1.860690   
3469                     3.541464                     3.212960   
3470                     1.857327                     8.079609   
3471                     2.367170                     8.599893   

      sensor_gravity_x_mean  sensor_gravity_y_mean  ...  \
0                 -0.055619               0.019945  ...   
1                  0.046793              -0.419544  ...   
2                 -0.022810              -0.040449  ...   
3                  0.372418              -8.557567  ...   
4                  0.521871              -9.633119  ...   
...                     ...                    ...  ...   
3467               0.101406               1.201873  ...   
3468              -1.510957               4.674029  ...   
3469              -0.133052               3.837788  ...   
3470              -1.385863               1.273659  ...   
3471              -1.003385               1.868450  ...   

      sensor_linear_acc_x_mean  sensor_linear_acc_y_mean  \
0                     0.000061                 -0.000091   
1                    -0.000513                  0.003966   
2                     0.000759                 -0.000138   
3                    -0.031159                 -0.110980   
4                     0.015729                 -0.063115   
...                        ...                       ...   
3467                 -0.030621                  0.181586   
3468                 -0.011051                  0.071136   
3469                 -0.017282                 -0.019066   
3470                 -0.035600                  0.038513   
3471                 -0.026457                  0.000925   

      sensor_linear_acc_z_mean  sensor_rotation_vec_x_mean  \
0                     0.126555                    0.002650   
1                     0.114253                   -0.027221   
2                     0.000673                   -0.00235

In [58]:
df.describe(include="all")

time_t_15  location_lat  location_lon  wifi_connected  \
count                  3472   3472.000000   3472.000000     3472.000000   
unique                 2829           NaN           NaN             NaN   
top     2018-03-19 16:45:00           NaN           NaN             NaN   
freq                      4           NaN           NaN             NaN   
mean                    NaN     43.708652     10.432839        0.733583   
std                     NaN      0.037014      0.072503        0.442149   
min                     NaN     43.550745     10.133765        0.000000   
25%                     NaN     43.701233     10.402318        0.000000   
50%                     NaN     43.711748     10.416229        1.000000   
75%                     NaN     43.715394     10.422036        1.000000   
max                     NaN     44.035693     11.188018        1.000000   

        sensor_light_mean  sensor_accelerometer_x_mean  \
count         3472.000000                  3472.000000   
unique                NaN                          NaN   
top                   NaN                          NaN   
freq                  NaN                          NaN   
mean          1111.782008                    -0.056702   
std           2528.371052                     1.705069   
min              0.266412                    -9.634776   
25%              4.422463                    -0.132999   
50%             46.226925                     0.010944   
75%            424.615000                     0.132982   
max          11991.744204                     9.446600   

        sensor_accelerometer_y_mean  sensor_accelerometer_z_mean  \
count                   3472.000000                  3472.000000   
unique                          NaN                          NaN   
top                             NaN                          NaN   
freq                            NaN                          NaN   
mean                      -0.339993                     7.972956   
std                        2.709244                     3.871981   
min                      -10.245785                    -9.702369   
25%                       -0.184738                     8.894475   
50%                        0.003945                     9.774540   
75%                        0.271500                     9.873627   
max                        9.583632                     9.979500   

        sensor_gravity_x_mean  sensor_gravity_y_mean  ...  \
count             3472.000000            3472.000000  ...   
unique                    NaN                    NaN  ...   
top                       NaN                    NaN  ...   
freq                      NaN                    NaN  ...   
mean                -0.054806              -0.295648  ...   
std                  1.677158               2.655397  ...   
min                 -9.538833              -9.708797  ...   
25%                 -0.133201              -0.183211  ...   
50%                  0.010068               0.007777  ...   
75%                  0.132585               0.282858  ...   
max                  9.399622               9.480608  ...   

        sensor_linear_acc_x_mean  sensor_linear_acc_y_mean  \
count                3472.000000               3472.000000   
unique                       NaN                       NaN   
top                          NaN                       NaN   
freq                         NaN                       NaN   
mean                   -0.001621                 -0.021378   
std                     0.112700                  0.166128   
min                    -1.605683                 -4.819243   
25%                    -0.003257                 -0.003901   
50%                    -0.000034                 -0.000187   
75%                     0.001574                  0.001326   
max                     2.183309                  1.215647   

        sensor_linear_acc_z_mean  sensor_rotation_vec_x_mean  \
count                3472.000000                 3472.000000 

In [59]:
#View the distribution of the dataset by transport mode class
print(df.groupby('activity_label').size())

activity_label
activity_rec_in_vehicle      28
activity_rec_on_bicycle      23
activity_rec_on_foot        227
activity_rec_still         3101
activity_rec_tilting          5
activity_rec_unknown         88
dtype: int64


In [60]:
#View the distribution of the dataset by purpose class (Não Temos!)
#print(df.groupby('purpose').size())

In [61]:
#Eliminate unique/or almost unique columns
df_final=df.drop(['time_t_15','location_lat','location_lon', 'uid'], axis=1)
df_final


wifi_connected  sensor_light_mean  sensor_accelerometer_x_mean  \
0                  0        6417.333333                    -0.055500   
1                  0        6040.027481                     0.047443   
2                  0         352.725761                    -0.011056   
3                  0        5661.303435                     0.342458   
4                  0          73.245882                     0.185271   
...              ...                ...                          ...   
3467               1          51.402142                     0.030118   
3468               1           2.614647                    -1.212274   
3469               1           3.052826                    -0.097346   
3470               1           4.598746                    -0.725779   
3471               1           2.310801                    -0.075510   

      sensor_accelerometer_y_mean  sensor_accelerometer_z_mean  \
0                        0.019917                     9.932985   
1                       -0.418751                     9.267274   
2                       -0.061413                     9.902697   
3                       -8.678619                    -0.115102   
4                       -9.787095                    -0.971805   
...                           ...                          ...   
3467                     1.358668                     9.230051   
3468                     5.196467                     1.860690   
3469                     3.541464                     3.212960   
3470                     1.857327                     8.079609   
3471                     2.367170                     8.599893   

      sensor_gravity_x_mean  sensor_gravity_y_mean  sensor_gravity_z_mean  \
0                 -0.055619               0.019945               9.806470   
1                  0.046793              -0.419544               9.149700   
2                 -0.022810              -0.040449               9.806376   
3                  0.372418              -8.557567              -0.165555   
4                  0.521871              -9.633119               0.366112   
...                     ...                    ...                    ...   
3467               0.101406               1.201873               9.370306   
3468              -1.510957               4.674029               2.211628   
3469              -0.133052               3.837788               3.551589   
3470              -1.385863               1.273659               8.869625   
3471              -1.003385               1.868450               8.726053   

      sensor_gyroscope_x_mean  sensor_gyroscope_y_mean  \
0                    0.041300                 0.007440   
1                    0.043922                 0.005525   
2                    0.000178                 0.000252   
3                    0.032933                -0.029124   
4                   -0.011428                -0.002609   
...                       ...                      ...   
3467                -0.012753                -0.000992   
3468                 0.006771                -0.010696   
3469                -0.008324                 0.005791   
3470                -0.008101                -0.000706   
3471                 0.001370                -0.011008   

      sensor_gyroscope_z_mean  sensor_linear_acc_x_mean  \
0                    0.002028                  0.000061   
1                    0.003902                 -0.000513   
2                    0.000055                  0.000759   
3                   -0.078405                 -0.031159   
4                    0.009619                  0.015729   
...                       ...                       ...   
3467                 0.007340                 -0.030621   
3468                 0.007310                 -0.011051   
3469                -0.000761                 -0.017282   
3470                 0.015987                 -0.035600   
3471                -0.015286                 -0.026457   

      sensor_line

In [62]:
#Simple Label encoding
#Import label encoder
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'activity_label'.
df_final['activity_label']= label_encoder.fit_transform(df_final['activity_label'])

df_final['activity_label'].unique()

array([3, 2, 5, 1, 4, 0])

In [63]:
# Encode labels in column 'label'.
df_final['label']= label_encoder.fit_transform(df_final['label'])

df_final['label'].unique()

array([9, 0, 1, 7, 2, 8, 3, 6, 4, 5])

In [64]:
#1º Classification problem - transport mode
Y1=df_final['activity_label'].to_numpy()  #1st possible dependent variable
type(Y1)

numpy.ndarray

In [65]:
#2nd Classification Problem - purpose
Y2=df_final['label'].to_numpy()  #2nd possible dependent variable

In [66]:
#Dependent variables are removed - 1st Problme
X1=df_final.drop(['activity_label','label'], axis=1).to_numpy()
print(X1)

[[ 0.00000000e+00  6.41733333e+03 -5.55000001e-02 ... -8.97856616e-04
  -9.29886806e-01  6.66666667e-01]
 [ 0.00000000e+00  6.04002748e+03  4.74430000e-02 ...  1.28876748e-02
  -8.82919280e-01  6.44444444e-01]
 [ 0.00000000e+00  3.52725761e+02 -1.10559082e-02 ...  1.22267015e-04
   4.45319168e-01  3.75022888e+00]
 ...
 [ 1.00000000e+00  3.05282600e+00 -9.73462016e-02 ...  1.09918935e-01
  -3.74904354e-02  2.40476190e+00]
 [ 1.00000000e+00  4.59874561e+00 -7.25778742e-01 ...  3.48569700e-02
  -1.71134475e-01  2.50000000e+00]
 [ 1.00000000e+00  2.31080084e+00 -7.55102370e-02 ... -5.33775216e-02
  -1.06709687e-01  3.05555556e+00]]


In [67]:
#Dependent variable is remove - 1st problem
X2=df_final.drop('label', axis=1).to_numpy()
print(X2)

[[ 0.00000000e+00  6.41733333e+03 -5.55000001e-02 ... -9.29886806e-01
   6.66666667e-01  3.00000000e+00]
 [ 0.00000000e+00  6.04002748e+03  4.74430000e-02 ... -8.82919280e-01
   6.44444444e-01  3.00000000e+00]
 [ 0.00000000e+00  3.52725761e+02 -1.10559082e-02 ...  4.45319168e-01
   3.75022888e+00  3.00000000e+00]
 ...
 [ 1.00000000e+00  3.05282600e+00 -9.73462016e-02 ... -3.74904354e-02
   2.40476190e+00  3.00000000e+00]
 [ 1.00000000e+00  4.59874561e+00 -7.25778742e-01 ... -1.71134475e-01
   2.50000000e+00  3.00000000e+00]
 [ 1.00000000e+00  2.31080084e+00 -7.55102370e-02 ... -1.06709687e-01
   3.05555556e+00  3.00000000e+00]]


In [68]:
#min-max normalization
import pandas as pd
# Min-Max Normalization function
def min_max_normalize(df2):
    return (df2 - df2.min()) / (df2.max() - df2.min())

# Apply Min-Max Normalization
X2 = min_max_normalize(X2)
X2

array([[0.00085367, 0.53554278, 0.00084905, ..., 0.0007762 , 0.00090922,
        0.00110363],
       [0.00085367, 0.50410584, 0.00085763, ..., 0.00078011, 0.00090737,
        0.00110363],
       [0.00085367, 0.03024261, 0.00085275, ..., 0.00089078, 0.00116614,
        0.00110363],
       ...,
       [0.00093699, 0.00110803, 0.00084556, ..., 0.00085055, 0.00105404,
        0.00110363],
       [0.00093699, 0.00123684, 0.0007932 , ..., 0.00083942, 0.00106197,
        0.00110363],
       [0.00093699, 0.00104621, 0.00084738, ..., 0.00084478, 0.00110826,
        0.00110363]])

In [69]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
# Split dataset into training set and test set
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, Y1, test_size=0.3,random_state=123) # 70% training and 30% test
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, Y2, test_size=0.3,random_state=123) # 70% training and 30% test

In [70]:
#Training and testing a decicion tree classifier - transport mode
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

clf1 = DecisionTreeClassifier().fit(X1_train, y1_train)
y1_pred=clf1.predict(X1_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y1_test, y1_pred))
print("F1-Score:",metrics.f1_score(y1_test, y1_pred, average='macro'))
print("Confusion Matrix:\n", metrics.confusion_matrix(y1_test, y1_pred))

Accuracy: 0.8973128598848369
F1-Score: 0.37050345695555276
Confusion Matrix:
 [[  1   0   3   5   0   1]
 [  0   4   0   0   0   1]
 [  2   9  45  19   1   4]
 [  2   4  13 879   0  21]
 [  0   0   1   0   0   0]
 [  0   4   2  15   0   6]]
